version: "3"
services:
  hub:
    build: 
      context: ./hub    
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    build: 
      context: ./node-chrome    
    container_name: selenium-node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_PORT: 5555
    ports:
      - "5555:5555"
  firefox:
    build: 
      context: ./node-firefox
    container_name: selenium-node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_PORT: 5556
    ports:
      - "5556:5556"